version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/front/
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 150
      runas: root
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 150
      runas: root
    - location: scripts/afterInstall2.sh
      timeout: 150
      runas: root
  ApplicationStart:
    - location: scripts/applicationStart.sh
      timeout: 150
      runas: root
# permissions:
#     - object: /
#       pattern: "**"
#       owner: ec2-user
#       group: ec2-user
